version: 1
accounts:
- name: alice
  coins:
  - 20000token
  - 10000cBTC
  - 200000000stake
  mnemonic: obvious bomb elbow report enable sketch night oblige gospel essay busy art
- name: bob
  coins:
  - 10000token
  - 10000cBTC
  - 100000000stake
faucet:
  name: bob
  coins:
  - 10000token
  - 21000000cBTC
  - 100000stake
client:
  typescript:
    path: ts-client
  composables:
    path: vue/src/composables
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 100000000stake
