// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fractal/fractal/exchange.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Exchange struct {
	Id         uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Finalunit  string `protobuf:"bytes,2,opt,name=finalunit,proto3" json:"finalunit,omitempty"`
	Amount     string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Startunit  string `protobuf:"bytes,4,opt,name=startunit,proto3" json:"startunit,omitempty"`
	Unitratio  string `protobuf:"bytes,5,opt,name=unitratio,proto3" json:"unitratio,omitempty"`
	Settledate string `protobuf:"bytes,6,opt,name=settledate,proto3" json:"settledate,omitempty"`
	State      string `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	Entity     string `protobuf:"bytes,8,opt,name=entity,proto3" json:"entity,omitempty"`
	Provider   string `protobuf:"bytes,9,opt,name=provider,proto3" json:"provider,omitempty"`
}

func (m *Exchange) Reset()         { *m = Exchange{} }
func (m *Exchange) String() string { return proto.CompactTextString(m) }
func (*Exchange) ProtoMessage()    {}
func (*Exchange) Descriptor() ([]byte, []int) {
	return fileDescriptor_1000ac10c29856a1, []int{0}
}
func (m *Exchange) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Exchange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Exchange.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Exchange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exchange.Merge(m, src)
}
func (m *Exchange) XXX_Size() int {
	return m.Size()
}
func (m *Exchange) XXX_DiscardUnknown() {
	xxx_messageInfo_Exchange.DiscardUnknown(m)
}

var xxx_messageInfo_Exchange proto.InternalMessageInfo

func (m *Exchange) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Exchange) GetFinalunit() string {
	if m != nil {
		return m.Finalunit
	}
	return ""
}

func (m *Exchange) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Exchange) GetStartunit() string {
	if m != nil {
		return m.Startunit
	}
	return ""
}

func (m *Exchange) GetUnitratio() string {
	if m != nil {
		return m.Unitratio
	}
	return ""
}

func (m *Exchange) GetSettledate() string {
	if m != nil {
		return m.Settledate
	}
	return ""
}

func (m *Exchange) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Exchange) GetEntity() string {
	if m != nil {
		return m.Entity
	}
	return ""
}

func (m *Exchange) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func init() {
	proto.RegisterType((*Exchange)(nil), "fractal.fractal.Exchange")
}

func init() { proto.RegisterFile("fractal/fractal/exchange.proto", fileDescriptor_1000ac10c29856a1) }

var fileDescriptor_1000ac10c29856a1 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x14, 0x45, 0x27, 0x63, 0x3b, 0xce, 0xbc, 0x85, 0x42, 0x10, 0x0d, 0x22, 0xa1, 0xb8, 0xea, 0xaa,
	0x22, 0xfe, 0x81, 0xe0, 0x0f, 0x74, 0xe9, 0x2e, 0x76, 0x5e, 0x35, 0x30, 0x26, 0x43, 0xe6, 0x55,
	0xda, 0xbf, 0xf0, 0xb3, 0x5c, 0x76, 0xe9, 0x52, 0x66, 0xfe, 0xc1, 0xb5, 0x24, 0x99, 0xc6, 0xae,
	0x2e, 0xf7, 0x9e, 0x77, 0xe1, 0x71, 0x41, 0xae, 0x9d, 0x5a, 0x91, 0x6a, 0xee, 0x0e, 0x8a, 0xdb,
	0xd5, 0x9b, 0x32, 0xaf, 0xb8, 0x68, 0x9d, 0x25, 0xcb, 0xcf, 0xc7, 0x7c, 0x31, 0xea, 0xed, 0x2f,
	0x83, 0xf2, 0x69, 0xbc, 0xe1, 0x67, 0x90, 0xeb, 0x5a, 0xb0, 0x19, 0x9b, 0x4f, 0x96, 0xb9, 0xae,
	0xf9, 0x0d, 0x54, 0x6b, 0x6d, 0x54, 0xb3, 0x31, 0x9a, 0x44, 0x3e, 0x63, 0xf3, 0x6a, 0xf9, 0x1f,
	0xf0, 0x4b, 0x28, 0xd4, 0xbb, 0xdd, 0x18, 0x12, 0x27, 0x01, 0x8d, 0xce, 0xb7, 0x3a, 0x52, 0x8e,
	0x42, 0x6b, 0x12, 0x5b, 0x29, 0xf0, 0xd4, 0xab, 0x53, 0xa4, 0xad, 0x98, 0x46, 0x9a, 0x02, 0x2e,
	0x01, 0x3a, 0x24, 0x6a, 0xb0, 0x56, 0x84, 0xa2, 0x08, 0xf8, 0x28, 0xe1, 0x17, 0x30, 0xed, 0xc8,
	0xa3, 0xd3, 0x80, 0xa2, 0xf1, 0x9f, 0xa0, 0x21, 0x4d, 0x3b, 0x51, 0xc6, 0x4f, 0xa2, 0xe3, 0xd7,
	0x50, 0xb6, 0xce, 0x7e, 0xe8, 0x1a, 0x9d, 0xa8, 0x02, 0x49, 0xfe, 0xf1, 0xfe, 0xab, 0x97, 0x6c,
	0xdf, 0x4b, 0xf6, 0xd3, 0x4b, 0xf6, 0x39, 0xc8, 0x6c, 0x3f, 0xc8, 0xec, 0x7b, 0x90, 0xd9, 0xf3,
	0xd5, 0x61, 0xbb, 0x6d, 0x5a, 0x91, 0x76, 0x2d, 0x76, 0x2f, 0x45, 0xd8, 0xf0, 0xe1, 0x2f, 0x00,
	0x00, 0xff, 0xff, 0x3d, 0xec, 0xa9, 0xbd, 0x65, 0x01, 0x00, 0x00,
}

func (m *Exchange) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Exchange) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Exchange) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Provider) > 0 {
		i -= len(m.Provider)
		copy(dAtA[i:], m.Provider)
		i = encodeVarintExchange(dAtA, i, uint64(len(m.Provider)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Entity) > 0 {
		i -= len(m.Entity)
		copy(dAtA[i:], m.Entity)
		i = encodeVarintExchange(dAtA, i, uint64(len(m.Entity)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.State) > 0 {
		i -= len(m.State)
		copy(dAtA[i:], m.State)
		i = encodeVarintExchange(dAtA, i, uint64(len(m.State)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Settledate) > 0 {
		i -= len(m.Settledate)
		copy(dAtA[i:], m.Settledate)
		i = encodeVarintExchange(dAtA, i, uint64(len(m.Settledate)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Unitratio) > 0 {
		i -= len(m.Unitratio)
		copy(dAtA[i:], m.Unitratio)
		i = encodeVarintExchange(dAtA, i, uint64(len(m.Unitratio)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Startunit) > 0 {
		i -= len(m.Startunit)
		copy(dAtA[i:], m.Startunit)
		i = encodeVarintExchange(dAtA, i, uint64(len(m.Startunit)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintExchange(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Finalunit) > 0 {
		i -= len(m.Finalunit)
		copy(dAtA[i:], m.Finalunit)
		i = encodeVarintExchange(dAtA, i, uint64(len(m.Finalunit)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintExchange(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintExchange(dAtA []byte, offset int, v uint64) int {
	offset -= sovExchange(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Exchange) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovExchange(uint64(m.Id))
	}
	l = len(m.Finalunit)
	if l > 0 {
		n += 1 + l + sovExchange(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovExchange(uint64(l))
	}
	l = len(m.Startunit)
	if l > 0 {
		n += 1 + l + sovExchange(uint64(l))
	}
	l = len(m.Unitratio)
	if l > 0 {
		n += 1 + l + sovExchange(uint64(l))
	}
	l = len(m.Settledate)
	if l > 0 {
		n += 1 + l + sovExchange(uint64(l))
	}
	l = len(m.State)
	if l > 0 {
		n += 1 + l + sovExchange(uint64(l))
	}
	l = len(m.Entity)
	if l > 0 {
		n += 1 + l + sovExchange(uint64(l))
	}
	l = len(m.Provider)
	if l > 0 {
		n += 1 + l + sovExchange(uint64(l))
	}
	return n
}

func sovExchange(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozExchange(x uint64) (n int) {
	return sovExchange(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Exchange) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowExchange
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Exchange: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Exchange: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExchange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Finalunit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExchange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExchange
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExchange
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Finalunit = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExchange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExchange
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExchange
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Startunit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExchange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExchange
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExchange
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Startunit = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Unitratio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExchange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExchange
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExchange
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Unitratio = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Settledate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExchange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExchange
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExchange
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Settledate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExchange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExchange
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExchange
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.State = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExchange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExchange
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExchange
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Entity = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExchange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExchange
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExchange
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Provider = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipExchange(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthExchange
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipExchange(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowExchange
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowExchange
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowExchange
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthExchange
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupExchange
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthExchange
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthExchange        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowExchange          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupExchange = fmt.Errorf("proto: unexpected end of group")
)
